version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: ./gradlew plugin:shadowJar
      - run: ./gradlew example:generateProto example:test
